export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  ADMIN_DASHBOARD: "/dashboard-admin",
  CATEGORIES: "/categories",
  ADD_CATEGORY: "/add-category",
  VENDOR_DASHBOARD: "/dashboard-vendor",
  VENDORS_LIST:"/vendors-list",
  RFP_LIST:"/rfp-list",
  QUOTES:"/rfp-quotes",
  ADD_RFP:"/add-rfp",
  RFP_FOR_QUOTES:"/rfp-for-quotes",
  APPLY_RFP:"/apply-rfp",
  REGISTER_ADMIN:"/register-admin",
  NOT_FOUND: "*",
};
